// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wshugmfkkbpwpxfakqgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzaHVnbWZra2Jwd3B4ZmFrcWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTExNTEsImV4cCI6MjA2NDc2NzE1MX0.uqoTSqp2LKlPgZbLMZKUlHYFcc9B9TeDmnDlx09wOnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);